[package]
name = "projection-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
core-lib = { version = "0.1.0", path = "../../libs/core-lib" }
proto = { version = "0.1.0", path = "../../libs/proto" }
tokio = { version = "1", features = ["full"] }
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"                                                  # For potential JSON logging or metadata
prost = "0.13"                                                      # For deserializing protobuf events
async-trait = "0.1"

# Dependencies for DB Migrations (Refinery) and eventual DB connection
refinery = { version = "0.8", features = ["tokio-postgres"] }
tokio-postgres = { version = "0.7", features = [
    "with-chrono-0_4",
    "with-uuid-1",
] } # Example features, adjust as needed
chrono = { version = "0.4", features = ["serde"] } # For timestamps
uuid = { version = "1.10", features = ["v4", "serde"] } # For IDs

# TODO: Add dependencies for actual event bus connection (e.g., lapin for RabbitMQ)
# TODO: Add dependencies for actual Redis connection (e.g., redis-rs)
