[package]
name = "api-gateway"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.8.3"
http = "1.3.1"
mime_guess = "2.0.5"
proto = { version = "0.1.0", path = "../../libs/proto" }
rust-embed = { version = "8.6.0", features = ["include-exclude"] }
tokio = { version = "1.44.2", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
